version: '3'
services:
  wordpress:
    image: wordpress
    container_name: servidor_wp
    ports:
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=bd_wp
      - WORDPRESS_DB_USER=user_wp
      - WORDPRESS_DB_PASSWORD=12345678
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: mariadb
    container_name: servidor_mariadb
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=12345678
      - MARIADB_DATABASE=bd_wp
      - MARIADB_USER=user_wp
      - MARIADB_PASSWORD=12345678
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8006:80
    environment: 
    #Con esta variable dejamos abierta la posibilidad de indicar un host en la interfaz web de phpMyadmin
      - PMA_ARBITRARY=1
      #- PMA_HOST=mariadb
    restart: always

volumes: 
  mariadb_data:
  wordpress_data: